repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
        exclude: ^(docs/|tests/)
  
  - repo: local
    hooks:
      - id: check-env-vars
        name: Check for exposed environment variables
        entry: bash -c 'if grep -r -E "(EMAIL_HOST_PASSWORD|TERMII_API_KEY|SECRET_KEY.*=.*[^=])(?!.*default)" --include="*.py" --include="*.md" .; then echo "🚨 Found exposed secrets!"; exit 1; fi'
        language: system
        pass_filenames: false
