# Generated by Django 5.2.4 on 2025-07-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0002_phonenumber_remove_comment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='phone_verified',
        ),
    ]
