# Generated by Django 5.0.3 on 2025-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0003_remove_phonenumber_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
