# Generated by Django 5.2.4 on 2025-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0004_phonenumber_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='termii_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
