# Generated by Django 5.0.3 on 2025-08-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0005_phonenumber_attempts_phonenumber_termii_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=10)),
                ('currency_to', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_account_name', models.CharField(max_length=100)),
                ('receiver_account_number', models.CharField(max_length=20)),
                ('receiver_bank', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastest_exchange.login')),
            ],
        ),
    ]
