# Generated by Django 5.0.3 on 2025-08-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0006_swapengine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swapengine',
            old_name='amount',
            new_name='amount_sent',
        ),
        migrations.AlterField(
            model_name='swapengine',
            name='receiver_account_number',
            field=models.CharField(max_length=100),
        ),
    ]
