# Generated by Django 5.0.3 on 2025-08-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0007_rename_amount_swapengine_amount_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swapengine',
            name='user',
        ),
    ]
