# Generated by Django 5.0.3 on 2025-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0008_remove_swapengine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapengine',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='swapengine',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='swapengine',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swapengine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='swapengine',
            name='verification_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
    ]
