# Generated by Django 5.0.3 on 2025-08-09 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0009_swapengine_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('beneficiary_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beneficiary_country', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_delivery_method', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.beneficiary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
