# Generated by Django 5.0.3 on 2025-08-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastest_exchange', '0011_kyc_reviewed_by_kyc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbeneficiary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_beneficiaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('SWAP', 'Currency Swap'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH_PICKUP', 'Cash Pickup'), ('KYC_SUBMISSION', 'KYC Submission'), ('BENEFICIARY_MANAGEMENT', 'Beneficiary Management')], max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REQUIRES_VERIFICATION', 'Requires Verification'), ('VERIFIED', 'Verified')], default='INITIATED', max_length=25)),
                ('amount_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_from', models.CharField(blank=True, max_length=10, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_to', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('bank_transfer_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.banktransfer')),
                ('beneficiary_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.savedbeneficiary')),
                ('cash_pickup_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.receivecash')),
                ('kyc_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.kyc')),
                ('mobile_money_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.mobilemoney')),
                ('swap_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fastest_exchange.swapengine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REQUIRES_VERIFICATION', 'Requires Verification'), ('VERIFIED', 'Verified')], max_length=25, null=True)),
                ('new_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REQUIRES_VERIFICATION', 'Requires Verification'), ('VERIFIED', 'Verified')], max_length=25)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='fastest_exchange.transaction')),
            ],
            options={
                'verbose_name_plural': 'Transaction Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='fastest_exc_transac_c197df_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='fastest_exc_user_id_f4eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='fastest_exc_status_0c5dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='fastest_exc_transac_39141d_idx'),
        ),
    ]
